# Generated by Django 5.0.1 on 2024-01-17 06:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('automatic_playback', models.BooleanField(default=False)),
                ('language', models.CharField(default='English', max_length=50)),
                ('age_rating', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_userprofile_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
