# Generated by Django 5.0.1 on 2024-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_usermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user',
            new_name='username',
        ),
    ]
