# Generated by Django 5.0.1 on 2024-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_user_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
