# Generated by Django 5.0.1 on 2024-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
