# Generated by Django 5.0.1 on 2024-01-23 10:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime.today)),
                ('last_play', models.DateTimeField(blank=True, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description_short', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('date_from', models.DateField()),
                ('video_length', models.CharField(blank=True, max_length=20, null=True)),
                ('movie_check', models.BooleanField(default=False)),
                ('short_movie_check', models.BooleanField(default=False)),
                ('nature_check', models.BooleanField(default=False)),
                ('funny_check', models.BooleanField(default=False)),
                ('knowledge_check', models.BooleanField(default=False)),
                ('other_check', models.BooleanField(default=False)),
                ('age_rating', models.PositiveIntegerField(default=0)),
                ('upload_visible_check', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploadMovie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
