# Generated by Django 5.0.1 on 2024-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmovie',
            name='big_picture',
            field=models.ImageField(blank=True, null=True, upload_to='big_picture/'),
        ),
        migrations.AddField(
            model_name='uploadmovie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='uploadmovie',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadmovie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
