# Generated by Django 5.0.1 on 2024-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_uploadmovie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='date_from',
            field=models.DateField(blank=True),
        ),
    ]
