# Generated by Django 5.0.1 on 2024-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_uploadmovie_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='date_from',
            field=models.DateField(null=True),
        ),
    ]
