# Generated by Django 5.0.1 on 2024-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_uploadmovie_date_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmovie',
            name='automatic_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadmovie',
            name='automatic_image',
            field=models.BooleanField(default=False),
        ),
    ]
