# Generated by Django 5.0.1 on 2024-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_uploadmovie_automatic_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmovie',
            name='convert_running',
            field=models.BooleanField(default=False),
        ),
    ]
