# Generated by Django 5.0.1 on 2024-02-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_uploadmovie_convert_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmovie',
            name='convert_running',
        ),
        migrations.AddField(
            model_name='uploadmovie',
            name='convert_status',
            field=models.IntegerField(default=0),
        ),
    ]
