# Generated by Django 5.0.1 on 2024-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_remove_uploadmovie_convert_running_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='cover',
            field=models.ImageField(default='static/load-142_256.gif', upload_to='cover/'),
        ),
    ]
